import type { ThemeConfig } from "antd";

export const solarGuardTokens = {
  colorPrimary: "#1688FF",
  colorSecondary: "#42E2C3",
  colorBackground: "#06111F",
  colorDeep: "#071524",
  colorHeader: "#071421",
  colorSurface: "#0D1E31",
  colorSurfaceRaised: "#102339",
  colorSurfaceHover: "#11263C",
  colorBorder: "#21415D",
  colorBorderSubtle: "#18324A",
  colorBorderStrong: "#2C5272",
  colorText: "#F2F7FC",
  colorTextSecondary: "#A9B7C7",
  colorTextMuted: "#778A9E",
  colorSuccess: "#31D48D",
  colorWarning: "#F3A62F",
  colorDanger: "#F54768",
  colorInfo: "#2F9BFF",
  colorRemote: "#9A65F7",
  colorField: "#2F9BFF",
  colorMonitoring: "#8293A6",
  colorUnknown: "#8293A6",
  priorityLow: "#31D48D",
  priorityMedium: "#2F9BFF",
  priorityHigh: "#F3A62F",
  priorityCritical: "#F54768",
  chartExpected: "#D8E4EF",
  chartActual: "#2F9BFF",
  chartIrradiance: "#8D56DD",
  chartGrid: "rgba(149, 176, 200, 0.14)",
  radiusSmall: 6,
  radiusMedium: 8,
  radiusLarge: 12,
};

export const antTheme: ThemeConfig = {
  token: {
    colorPrimary: solarGuardTokens.colorPrimary,
    colorInfo: solarGuardTokens.colorInfo,
    colorSuccess: solarGuardTokens.colorSuccess,
    colorWarning: solarGuardTokens.colorWarning,
    colorError: solarGuardTokens.colorDanger,
    colorBgLayout: solarGuardTokens.colorBackground,
    colorBgContainer: solarGuardTokens.colorSurface,
    colorBgElevated: solarGuardTokens.colorSurfaceRaised,
    colorBorder: solarGuardTokens.colorBorder,
    colorText: solarGuardTokens.colorText,
    colorTextSecondary: solarGuardTokens.colorTextSecondary,
    colorLink: solarGuardTokens.colorPrimary,
    borderRadius: solarGuardTokens.radiusMedium,
    borderRadiusLG: solarGuardTokens.radiusLarge,
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
    fontSize: 14,
    lineHeight: 1.45,
    controlHeight: 36,
  },
  components: {
    Button: {
      borderRadius: 8,
      fontWeight: 600,
      primaryShadow: "0 0 20px rgba(22, 136, 255, 0.22)",
    },
    Card: {
      borderRadiusLG: solarGuardTokens.radiusLarge,
      paddingLG: 16,
      boxShadowTertiary: "none",
      colorBgContainer: solarGuardTokens.colorSurface,
      colorBorderSecondary: solarGuardTokens.colorBorderSubtle,
    },
    Layout: {
      bodyBg: solarGuardTokens.colorBackground,
      headerBg: solarGuardTokens.colorHeader,
      siderBg: solarGuardTokens.colorHeader,
    },
    Table: {
      headerBg: "#0A1929",
      borderColor: solarGuardTokens.colorBorderSubtle,
      cellPaddingBlock: 8,
      cellPaddingInline: 10,
      colorBgContainer: solarGuardTokens.colorSurface,
      colorText: solarGuardTokens.colorTextSecondary,
      colorTextHeading: solarGuardTokens.colorTextMuted,
    },
    Select: {
      selectorBg: "#0b1928",
      optionSelectedBg: "rgba(22, 136, 255, 0.22)",
      optionActiveBg: "rgba(22, 136, 255, 0.12)",
      optionSelectedColor: solarGuardTokens.colorText,
      colorTextPlaceholder: solarGuardTokens.colorTextMuted,
      colorText: solarGuardTokens.colorText,
      colorBgElevated: solarGuardTokens.colorSurfaceRaised,
      colorBorder: solarGuardTokens.colorBorderSubtle,
      hoverBorderColor: solarGuardTokens.colorBorderStrong,
      activeBorderColor: solarGuardTokens.colorPrimary,
      activeOutlineColor: "rgba(22, 136, 255, 0.18)",
    },
    Tag: {
      borderRadiusSM: solarGuardTokens.radiusSmall,
    },
  },
};
