import type { ServiceQueue } from "../src/api/schemas/decisions";
import type { FleetSummary, FleetTimeseries } from "../src/api/schemas/fleet";
import type { LatestRoutePlan } from "../src/api/schemas/routes";
import type { SiteDiagnostics, SiteSummary } from "../src/api/schemas/sites";

export const fleetSummaryFixture: FleetSummary = {
  analysis_run_id: "RUN-FRONTEND",
  monitored_sites: 30,
  healthy_sites: 17,
  attention_sites: 13,
  communication_issues: 3,
  insufficient_evidence: 4,
  remote_actions: 5,
  field_visits: 4,
  estimated_energy_value_at_risk_inr: 1930.46,
  estimated_recoverable_energy_kwh: 70.178,
  estimated_recoverable_value_inr: 561.92,
  top_priority_site_id: "SITE-TOP",
};

export const serviceQueueFixture: ServiceQueue = {
  analysis_run_id: "RUN-FRONTEND",
  count: 5,
  items: [
    {
      decision_id: "SD-001",
      analysis_run_id: "RUN-FRONTEND",
      incident_candidate_id: "IC-001",
      site_id: "SITE-TOP",
      probable_issue: "probable inverter or grid-side interruption",
      confidence_score: 84,
      confidence_label: "High",
      supporting_evidence: ["Strong daylight outage pattern"],
      contradictory_evidence: [],
      expected_energy_kwh: 15,
      actual_energy_kwh: 3,
      estimated_energy_loss_kwh: 12,
      estimated_value_at_risk_inr: 94,
      projected_seven_day_loss_kwh: 41,
      estimated_recoverable_energy_kwh: 26,
      estimated_recoverable_value_inr: 195,
      cleaning_decision: "not_applicable",
      recommended_action: "urgent field visit",
      escalation_condition: "Dispatch after remote restart fails.",
      remote_action_available: true,
      visit_required: true,
      actionable: true,
      priority_score: 81,
      priority_label: "Critical",
      queue_rank: 1,
      created_at: "2026-07-04T12:00:00Z",
    },
    {
      decision_id: "SD-002",
      analysis_run_id: "RUN-FRONTEND",
      incident_candidate_id: "IC-002",
      site_id: "SITE-REMOTE",
      probable_issue: "communication or data-logger failure",
      confidence_score: 89,
      confidence_label: "Very high",
      supporting_evidence: ["Telemetry not received"],
      contradictory_evidence: [],
      expected_energy_kwh: 0,
      actual_energy_kwh: null,
      estimated_energy_loss_kwh: 0,
      estimated_value_at_risk_inr: 0,
      projected_seven_day_loss_kwh: 0,
      estimated_recoverable_energy_kwh: 0,
      estimated_recoverable_value_inr: 0,
      cleaning_decision: "not_applicable",
      recommended_action: "remote connectivity check",
      escalation_condition: "Dispatch if remote recovery fails.",
      remote_action_available: true,
      visit_required: false,
      actionable: true,
      priority_score: 47,
      priority_label: "Medium",
      queue_rank: 2,
      created_at: "2026-07-04T12:00:00Z",
    },
    {
      decision_id: "SD-003",
      analysis_run_id: "RUN-FRONTEND",
      incident_candidate_id: "IC-003",
      site_id: "SITE-MONITOR",
      probable_issue: "unknown or insufficient evidence",
      confidence_score: 36,
      confidence_label: "Low",
      supporting_evidence: ["Evidence is incomplete"],
      contradictory_evidence: ["Signals conflict"],
      expected_energy_kwh: 10,
      actual_energy_kwh: 8,
      estimated_energy_loss_kwh: 2,
      estimated_value_at_risk_inr: 16,
      projected_seven_day_loss_kwh: 5,
      estimated_recoverable_energy_kwh: 1,
      estimated_recoverable_value_inr: 8,
      cleaning_decision: "not_applicable",
      recommended_action: "collect additional data",
      escalation_condition: "Escalate if evidence improves.",
      remote_action_available: true,
      visit_required: false,
      actionable: false,
      priority_score: 36,
      priority_label: "Low",
      queue_rank: null,
      created_at: "2026-07-04T12:00:00Z",
    },
    {
      decision_id: "SD-004",
      analysis_run_id: "RUN-FRONTEND",
      incident_candidate_id: "IC-004",
      site_id: "SITE-GRADUAL",
      probable_issue: "gradual persistent underperformance",
      confidence_score: 71,
      confidence_label: "High",
      supporting_evidence: ["Clear-sky output declined across comparable intervals"],
      contradictory_evidence: [],
      expected_energy_kwh: 18,
      actual_energy_kwh: 10,
      estimated_energy_loss_kwh: 8,
      estimated_value_at_risk_inr: 64,
      projected_seven_day_loss_kwh: 56,
      estimated_recoverable_energy_kwh: 33,
      estimated_recoverable_value_inr: 210,
      cleaning_decision: "schedule_cleaning",
      recommended_action: "run remote performance diagnostics",
      escalation_condition: "Schedule cleaning or inspection if trend persists.",
      remote_action_available: true,
      visit_required: false,
      actionable: true,
      priority_score: 68,
      priority_label: "Medium",
      queue_rank: 3,
      created_at: "2026-07-04T12:00:00Z",
    },
    {
      decision_id: "SD-005",
      analysis_run_id: "RUN-FRONTEND",
      incident_candidate_id: "IC-005",
      site_id: "SITE-TIME",
      probable_issue: "time-specific underperformance",
      confidence_score: 64,
      confidence_label: "Medium",
      supporting_evidence: ["Loss repeats in the same daylight window"],
      contradictory_evidence: [],
      expected_energy_kwh: 14,
      actual_energy_kwh: 8,
      estimated_energy_loss_kwh: 6,
      estimated_value_at_risk_inr: 48,
      projected_seven_day_loss_kwh: 42,
      estimated_recoverable_energy_kwh: 20,
      estimated_recoverable_value_inr: 126,
      cleaning_decision: "not_applicable",
      recommended_action: "check environment and shading patterns",
      escalation_condition: "Review site photos before field inspection.",
      remote_action_available: false,
      visit_required: true,
      actionable: true,
      priority_score: 60,
      priority_label: "Medium",
      queue_rank: 4,
      created_at: "2026-07-04T12:00:00Z",
    },
  ],
};

export const latestRouteFixture: LatestRoutePlan = {
  route_plan_id: "RP-FRONTEND",
  analysis_run_id: "RUN-FRONTEND",
  planning_date: "2026-07-05",
  optimisation_status: "optimized",
  failure_reason: null,
  field_plan: [
    {
      technician_id: "TECH-01",
      technician_name: "Rohit S.",
      shift_start: "09:00:00",
      shift_end: "18:00:00",
      region: "Pune",
      skills: ["inverter", "grid"],
      distance_km: 18,
      travel_duration_min: 40,
      job_duration_min: 130,
      return_to_hub: true,
      stops: [
        {
          technician_id: "TECH-01",
          sequence: 1,
          job: {
            decision_id: "SD-001",
            candidate_id: "IC-001",
            site_id: "SITE-TOP",
            latitude: 18.5,
            longitude: 73.9,
            priority_score: 81,
            priority_label: "High",
            probable_issue: "probable inverter or grid-side interruption",
            recommended_action: "urgent field visit",
            required_skills: ["electrical"],
            duration_min: 90,
            recoverable_energy_kwh: 72.6,
            recoverable_value_inr: 195,
            escalation_deadline: null,
            earliest_service_time: null,
          },
          arrival: "2026-07-05T09:15:00+05:30",
          departure: "2026-07-05T10:15:00+05:30",
          travel_distance_km: 8,
          travel_duration_min: 15,
        },
        {
          technician_id: "TECH-01",
          sequence: 2,
          job: {
            decision_id: "SD-006",
            candidate_id: "IC-006",
            site_id: "SITE-HORIZON",
            latitude: 18.56,
            longitude: 73.8,
            priority_score: 74,
            priority_label: "High",
            probable_issue: "probable grid-side interruption",
            recommended_action: "verify grid and inverter status",
            required_skills: ["inverter", "grid"],
            duration_min: 70,
            recoverable_energy_kwh: 56,
            recoverable_value_inr: 168,
            escalation_deadline: null,
            earliest_service_time: null,
          },
          arrival: "2026-07-05T10:35:00+05:30",
          departure: "2026-07-05T11:45:00+05:30",
          travel_distance_km: 10,
          travel_duration_min: 25,
        },
      ],
    },
    {
      technician_id: "TECH-02",
      technician_name: "Neha P.",
      shift_start: "09:00:00",
      shift_end: "18:00:00",
      region: "Pune",
      skills: ["electrical", "inspection"],
      distance_km: 29,
      travel_duration_min: 55,
      job_duration_min: 165,
      return_to_hub: true,
      stops: [
        {
          technician_id: "TECH-02",
          sequence: 1,
          job: {
            decision_id: "SD-004",
            candidate_id: "IC-004",
            site_id: "SITE-GRADUAL",
            latitude: 18.47,
            longitude: 73.85,
            priority_score: 68,
            priority_label: "Medium",
            probable_issue: "gradual persistent underperformance",
            recommended_action: "inspect strings and evaluate cleaning",
            required_skills: ["electrical", "inspection"],
            duration_min: 90,
            recoverable_energy_kwh: 98.4,
            recoverable_value_inr: 210,
            escalation_deadline: null,
            earliest_service_time: null,
          },
          arrival: "2026-07-05T09:25:00+05:30",
          departure: "2026-07-05T10:55:00+05:30",
          travel_distance_km: 13,
          travel_duration_min: 25,
        },
        {
          technician_id: "TECH-02",
          sequence: 2,
          job: {
            decision_id: "SD-007",
            candidate_id: "IC-007",
            site_id: "SITE-WESTVIEW-FIELD",
            latitude: 18.49,
            longitude: 73.83,
            priority_score: 62,
            priority_label: "Medium",
            probable_issue: "time-specific underperformance",
            recommended_action: "inspect obstruction and shading window",
            required_skills: ["electrical", "inspection"],
            duration_min: 75,
            recoverable_energy_kwh: 85,
            recoverable_value_inr: 178,
            escalation_deadline: null,
            earliest_service_time: null,
          },
          arrival: "2026-07-05T11:20:00+05:30",
          departure: "2026-07-05T12:35:00+05:30",
          travel_distance_km: 16,
          travel_duration_min: 30,
        },
      ],
    },
  ],
  remote_action_queue: [
    {
      decision_id: "SD-002",
      site_id: "SITE-REMOTE",
      probable_issue: "communication or data-logger failure",
      recommended_action: "remote connectivity check",
      actionable: true,
      remote_action_available: true,
      visit_required: false,
      priority_score: 47,
      priority_label: "Medium",
    },
  ],
  monitoring_queue: [
    {
      decision_id: "SD-003",
      site_id: "SITE-MONITOR",
      probable_issue: "unknown or insufficient evidence",
      recommended_action: "collect additional data",
      actionable: false,
      remote_action_available: true,
      visit_required: false,
      priority_score: 36,
      priority_label: "Low",
    },
  ],
  unassigned_jobs: [],
  naive_routes: [["SITE-TOP", "SITE-HORIZON"], ["SITE-GRADUAL", "SITE-WESTVIEW-FIELD"]],
  total_eligible_jobs: 4,
  assigned_jobs: 4,
  unassigned_jobs_count: 0,
  naive_distance_km: 68,
  optimised_distance_km: 47,
  distance_avoided_km: 21,
  total_travel_duration_min: 95,
  total_job_duration_min: 295,
  total_recoverable_energy_kwh: 312,
  total_recoverable_value_inr: 751,
};

export const fleetTimeseriesFixture: FleetTimeseries = {
  analysis_run_id: "RUN-FRONTEND",
  items: [
    {
      timestamp: "2026-07-04T08:00:00Z",
      expected_generation_kwh: 12,
      actual_generation_kwh: 10,
      energy_loss_kwh: 2,
      ghi_wm2: 500,
    },
  ],
};

export const sitesFixture: SiteSummary[] = [
  {
    site_id: "SITE-TOP",
    site_name: "Greenfield Farm",
    capacity_kw: 5,
    latitude: 18.5,
    longitude: 73.9,
    weather_zone: "PUNE",
    azimuth_degree: 180,
    tariff_per_kwh: 8,
    service_region: "Pune",
    customer_type: "residential",
    warranty_end_date: "2027-01-01",
    cleaning_cost_inr: 700,
    visit_cost_inr: 800,
    analysis_run_id: "RUN-FRONTEND",
    status: "attention",
    probable_issue: "probable inverter or grid-side interruption",
    priority_label: "High",
    priority_score: 81,
    actionable: true,
  },
  {
    site_id: "SITE-REMOTE",
    site_name: "Mountain Retreat",
    capacity_kw: 25,
    latitude: 18.58,
    longitude: 73.81,
    weather_zone: "PUNE",
    azimuth_degree: 175,
    tariff_per_kwh: 8,
    service_region: "Pune West",
    customer_type: "commercial",
    warranty_end_date: "2027-01-01",
    cleaning_cost_inr: 750,
    visit_cost_inr: 800,
    analysis_run_id: "RUN-FRONTEND",
    status: "attention",
    probable_issue: "communication or data-logger failure",
    priority_label: "Medium",
    priority_score: 47,
    actionable: true,
  },
  {
    site_id: "SITE-MONITOR",
    site_name: "Shree Plaza",
    capacity_kw: 50,
    latitude: 18.53,
    longitude: 73.87,
    weather_zone: "PUNE",
    azimuth_degree: 182,
    tariff_per_kwh: 8,
    service_region: "Pune East",
    customer_type: "commercial",
    warranty_end_date: "2027-01-01",
    cleaning_cost_inr: 750,
    visit_cost_inr: 800,
    analysis_run_id: "RUN-FRONTEND",
    status: "attention",
    probable_issue: "unknown or insufficient evidence",
    priority_label: "Low",
    priority_score: 36,
    actionable: false,
  },
  {
    site_id: "SITE-HEALTHY",
    site_name: "Westview School",
    capacity_kw: 80,
    latitude: 18.49,
    longitude: 73.83,
    weather_zone: "PUNE",
    azimuth_degree: 180,
    tariff_per_kwh: 8,
    service_region: "Pune East",
    customer_type: "commercial",
    warranty_end_date: "2027-01-01",
    cleaning_cost_inr: 750,
    visit_cost_inr: 800,
    analysis_run_id: "RUN-FRONTEND",
    status: "healthy",
    probable_issue: null,
    priority_label: null,
    priority_score: null,
    actionable: false,
  },
  {
    site_id: "SITE-GRADUAL",
    site_name: "Lakeside Office",
    capacity_kw: 100,
    latitude: 18.47,
    longitude: 73.85,
    weather_zone: "PUNE",
    azimuth_degree: 178,
    tariff_per_kwh: 8,
    service_region: "Pune North",
    customer_type: "commercial",
    warranty_end_date: "2027-01-01",
    cleaning_cost_inr: 750,
    visit_cost_inr: 800,
    analysis_run_id: "RUN-FRONTEND",
    status: "attention",
    probable_issue: "gradual persistent underperformance",
    priority_label: "Medium",
    priority_score: 68,
    actionable: true,
  },
  {
    site_id: "SITE-TIME",
    site_name: "Sunset Residence",
    capacity_kw: 15,
    latitude: 18.56,
    longitude: 73.8,
    weather_zone: "PUNE",
    azimuth_degree: 182,
    tariff_per_kwh: 8,
    service_region: "Pune West",
    customer_type: "residential",
    warranty_end_date: "2027-01-01",
    cleaning_cost_inr: 700,
    visit_cost_inr: 800,
    analysis_run_id: "RUN-FRONTEND",
    status: "attention",
    probable_issue: "time-specific underperformance",
    priority_label: "Medium",
    priority_score: 60,
    actionable: true,
  },
  {
    site_id: "SITE-HORIZON",
    site_name: "Sunset Residence",
    capacity_kw: 15,
    latitude: 18.56,
    longitude: 73.8,
    weather_zone: "PUNE",
    azimuth_degree: 180,
    tariff_per_kwh: 8,
    service_region: "Pune West",
    customer_type: "residential",
    warranty_end_date: "2027-01-01",
    cleaning_cost_inr: 700,
    visit_cost_inr: 800,
    analysis_run_id: "RUN-FRONTEND",
    status: "attention",
    probable_issue: "probable grid-side interruption",
    priority_label: "High",
    priority_score: 74,
    actionable: true,
  },
  {
    site_id: "SITE-WESTVIEW-FIELD",
    site_name: "Westview School",
    capacity_kw: 80,
    latitude: 18.49,
    longitude: 73.83,
    weather_zone: "PUNE",
    azimuth_degree: 180,
    tariff_per_kwh: 8,
    service_region: "Pune East",
    customer_type: "commercial",
    warranty_end_date: "2027-01-01",
    cleaning_cost_inr: 750,
    visit_cost_inr: 800,
    analysis_run_id: "RUN-FRONTEND",
    status: "attention",
    probable_issue: "time-specific underperformance",
    priority_label: "Medium",
    priority_score: 62,
    actionable: true,
  },
];

export const siteDiagnosticsFixture: SiteDiagnostics = {
  analysis_run_id: "RUN-FRONTEND",
  site: {
    site_id: "SITE-TOP",
    site_name: "Greenfield Farm",
    capacity_kw: 5,
    latitude: 18.5,
    longitude: 73.9,
    weather_zone: "PUNE",
    azimuth_degree: 180,
    tariff_per_kwh: 8,
    service_region: "Pune",
    customer_type: "residential",
    warranty_end_date: "2027-01-01",
    cleaning_cost_inr: 700,
    visit_cost_inr: 800,
  },
  diagnostics: [
    {
      decision: serviceQueueFixture.items[0],
      candidate: {
        incident_candidate_id: "IC-001",
        start_timestamp: "2026-07-04T10:09:00+05:30",
        end_timestamp: "2026-07-04T10:18:00+05:30",
        duration_intervals: 6,
        persistence_intervals: 6,
        anomaly_type: "sudden outage",
        severity: "medium",
      },
    },
  ],
  performance: [
    {
      timestamp: "2026-07-04T09:00:00+05:30",
      expected_generation_kwh: 4,
      actual_generation_kwh: 3.8,
      signed_residual_kwh: -0.2,
      energy_loss_kwh: 0.2,
      performance_ratio: 0.95,
      ghi_wm2: 620,
      anomaly_state: "normal",
      data_quality_status: "good",
    },
    {
      timestamp: "2026-07-04T10:15:00+05:30",
      expected_generation_kwh: 4.21,
      actual_generation_kwh: 0.05,
      signed_residual_kwh: -4.16,
      energy_loss_kwh: 4.16,
      performance_ratio: 0.01,
      ghi_wm2: 726,
      anomaly_state: "sudden_outage",
      data_quality_status: "good",
    },
  ],
};
